### PR TITLE
Add ability to use either spelling of defence / defense

### PR DESCRIPTION
**Pull request by jackbrown1993**

### CODE REVIEW

**Comment by Coffee-fueled-deadlines** [comment]
This will error out when you do `user.skill('defense')` or `user.skill('defense')` as you've put `if skill = 'defense': skill = 'defence'` but left it spelled `defense` in the skills list.  I suggest swapping those around and doing `if skill = 'defence': skill = 'defense'` instead.

**Comment by Coffee-fueled-deadlines** [comment]
Check the above workflow:

```
=========================== short test summary info ============================
FAILED OSRSBytes/tests/hiscores_test.py::test - OSRSBytes.Hiscores.SkillError: ERROR: skill 'defence' does not exist
==================== 1 failed, 1 passed, 1 warning in 3.61s ====================
```

**Comment by jackbrown1993** [comment]
How do you run the tests?

**Comment by jackbrown1993** [comment]
> This will error out when you do `user.skill('defense')` or `user.skill('defense')` as you've put `if skill = 'defense': skill = 'defence'` but left it spelled `defense` in the skills list. I suggest swapping those around and doing `if skill = 'defence': skill = 'defense'` instead.

I think I did this in the original pull request my bad... will fix and start paying more attention :)

**Comment by Coffee-fueled-deadlines** [comment]
> How do you run the tests?

The tests are available to run when a Pull request is made.  I think I have to approve them but I could look into modifying that.  If you forked it, they should appear under `actions` at the top

**Pull request closed without merging**
