### PR TITLE
Add 'total' as a skill

### PR DESCRIPTION
**Pull request by jackbrown1993**
@Coffee-fueled-deadlines are you happy for the total to be processed as a skill so handling for level, rank and XP is consistent? Also seems to fix issue I was facing in #46

### CODE REVIEW

**Comment by Coffee-fueled-deadlines** [comment]
Total is already handled as a skill, see attached screenshot:

image

**Comment by jackbrown1993** [comment]
As per your screenshot and #46 the XP shown for total is wrong. What is \n1211768

**Comment by Coffee-fueled-deadlines** [comment]
> As per your screenshot and #46 the XP shown for total is wrong. What is \n1211768

That part is an error, correct.  However `total` is already handled as a skill.

[Total processing begins here](https://github.com/Coffee-fueled-deadlines/OSRSBytes/blob/master/OSRSBytes/Hiscores.py#L168-L182)

and then it's added to the skills dictionary [here](https://github.com/Coffee-fueled-deadlines/OSRSBytes/blob/master/OSRSBytes/Hiscores.py#L233)

In your branch [here](https://github.com/Coffee-fueled-deadlines/OSRSBytes/compare/master...jackbrown1993:OSRSBytes:updated_total_calculation) the removal of the `pop(0)` is removing the removal of redundant data that was already calculated and added `total` into the skills as you have would just result in the `total` being overwritten again with a new `total` key.

**Comment by Coffee-fueled-deadlines** [comment]
Pull request must be made to `dev` not `master`.  Ensure that all changes on your end are done to `dev` as well.  Master is only updated when a new release is made. 

In addition to what was stated above, please make sure you're working in `dev` and not on `master` directly.  For this pull request, I honestly suggest just parsing off the `\n` with something like 

```
info['experience'] = total_info[2].split("\n",1)[0]
```

**Pull request closed without merging**
